services:
  auth-service:
    image: corebank-auth:dev
    container_name: corebank-auth
    ports:
      - "8080:8080"
    environment:
      AUTH_JWT_SECRET: this-is-a-dev-secret-change-me-32-chars-minimum!!
    restart: unless-stopped

  accounts-service:
    image: corebank-accounts:dev
    container_name: corebank-accounts
    ports:
      - "8081:8081"
    environment:
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
    restart: unless-stopped
